media:
  input: "image"
  output: "/image"

content:
  - name: "newsletter"
    label: "Newsletter Section"
    type: "file"
    path: "data/newsletter.json"
    format: "json"
    fields:
      - name: "news_list"
        label: "Newsletter Items"
        type: "list"
        fields:
          - name: "text"
            label: "Message"
            type: "text"
          - name: "backgroundColor"
            label: "Background Color"
            type: "color"
          - name: "textColor"
            label: "Text Color"
            type: "color"
          - name: "fontFamily"
            label: "Font"
            type: "select"
            options:
              - "Ortica Linear"
              - "Ronzino Bold"
              - "sans-serif"
          - name: "fontSize"
            label: "Font Size"
            type: "string"
            default: "1.2rem"
