media:
  input: image
  output: image

content:
  - name: newsletter
    label: Newsletter Cards
    type: collection
    path: content/newsletter
    format: json
    fields:
      - name: text
        label: Message
        type: string
        required: true
      - name: backgroundColor
        label: Background Color
        type: color
      - name: textColor
        label: Text Color
        type: color
      - name: fontFamily
        label: Font Name
        type: string
        default: "sans-serif"
        hint: "Type 'Ortica Linear', 'Ronzino Bold', or 'sans-serif'"
      - name: fontSize
        label: Font Size
        type: string
        default: "1.2rem"
