media:
  input: image
  output: image

content:
  - name: newsletter
    label: Newsletter Cards
    type: collection
    path: content/newsletter
    format: json
    extension: json
    slug: "{{slug}}"
    fields:
      - name: slug
        label: "Card Number (Enter 1, 2, 3...)"
        type: string
        required: true
        pattern: "^[0-9]+$"
        hint: "This MUST be a number like 1, 2, or 3."
      - name: text
        label: Message
        type: string
        required: true
      - name: backgroundColor
        label: Background Color
        type: color
      - name: textColor
        label: Text Color
        type: color
      - name: fontFamily
        label: Font Name
        type: string
        default: "sans-serif"
      - name: fontSize
        label: Font Size
        type: string
        default: "1.2rem"
