collections:
  - name: "newsletter"
    label: "Newsletter"
    file: "content/newsletter.json"
    create: true
    fields:
      - name: "items"
        label: "Newsletter Items"
        type: "list"
        fields:
          - { name: text, label: Text, type: string, required: true}
          - { name: color, label: Color, type: string, required: true}
          - { name: top, label: Top, type: number, required: true }
          - { name: left, label: Left, type: number, required: true }
