media:
  input: image
  output: /image

content:
  - name: newsletter
    label: Newsletter Section
    type: file
    path: data/newsletter.json
    fields:
      - name: items
        label: Newsletter Cards
        type: list
        fields:
          - name: text
            label: Message
            type: string
          - name: backgroundColor
            label: Background Color
            type: color
          - name: textColor
            label: Text Color
            type: color
          - name: fontFamily
            label: Font Name
            type: string
